[[crates]]
name = "chipmunk"
source = "crates"

[[crates]]
name = "collider"
source = "crates"

[[crates]]
name = "liquidfun"
source = "crates"

[[crates]]
name = "mgf"
source = "crates"

[[crates]]
name = "ncollide"
source = "crates"
homepage = "https://ncollide.org"

[[crates]]
name = "nphysics2d"
source = "crates"
homepage = "https://nphysics.org"

[[crates]]
name = "nphysics3d"
source = "crates"
homepage = "https://nphysics.org"

[[crates]]
name = "physx"
source = "crates"
homepage = "https://github.com/EmbarkStudios/physx-rs"

[[crates]]
name = "rhusics"
source = "crates"

[[crates]]
name = "salva2d"
source = "crates"
homepage = "https://salva.rs"

[[crates]]
name = "salva3d"
source = "crates"
homepage = "https://salva.rs"

[[crates]]
name = "wrapped2d"
source = "crates"

